version: "3.5"
services:
  # creating couchbase docker compose files
  # define couchbase 1
  couchbase1:
  # get the image from the couchbase/server
    image: couchbase:community-6.6.0
    container_name: couchbase1
    volumes:
      - ~/couchbase/node1:/opt/couchbase/var
    network_mode: "host"
